# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X65DbUChiawIbEdoF--8cFRO9rsMF3P_
"""

import pandas as pd
import numpy as np
import cv2
from tqdm import tqdm
import json 

import torch
from torch.utils.data import DataLoader
from torchvision import models
from torchsummary import summary

import torchvision
from torchvision import transforms
from torch.utils.data import Dataset, DataLoader
from torch.optim.lr_scheduler import ReduceLROnPlateau, MultiStepLR
from torch.utils.data import random_split
import torch.optim as optim


from torchsummary import summary
import torch.nn as nn
import torch.nn.functional as F

import matplotlib.pyplot as plt
import os
import shutil

!unzip /content/drive/MyDrive/tiny-imagenet-200.zip

base = "/content/tiny-imagenet-200/train"
cnt = 0
for root in os.listdir(base):
    cnt = 0

    eachClass = base + "/" + root + "/images"
    for eachImg in os.listdir(eachClass):
        if cnt > 24:
            break

        shutil.copyfile(eachClass + "/" + eachImg, "/content/dataset/train/"+ eachImg )
        cnt+=1

base = "/content/tiny-imagenet-200/val/images"
cnt = 0
for eachImg in os.listdir(base):
    if cnt >= 1300:
        break

    shutil.copyfile(base + "/" + eachImg, "/content/dataset/test/"+ eachImg )
    cnt+=1

cnt = 0
for root in os.listdir("/content/dataset/train"):
  #os.remove("/content/dataset/train/" + root)
  cnt+=1
cnt
print(cnt)
cnt = 0
for root in os.listdir("/content/dataset/test"):
  #os.remove("/content/dataset/test/" + root)
  cnt+=1
cnt

data = {"path" : []}

for root in os.listdir("/content/dataset/train"):
    if root[-1] == "G":
      data["path"].append(root)

pd.DataFrame.from_dict(data).to_csv("/content/dataset/trainData.csv")

data = {"path" : []}

for root in os.listdir("/content/dataset/test"):
    if root[-1] == "G":
      data["path"].append(root)

pd.DataFrame.from_dict(data).to_csv("/content/dataset/testData.csv")

